package elder.leapp.transfer;

// TransferSession.java
// A data object holding the state of one in-progress connection attempt.
// One instance is created per active transfer. Discarded on completion or failure.
// TransferOrchestrator owns all session instances.

public class TransferSession {

    // All possible states a transfer session can be in.
    // Progress moves forward through these in order; any failure discards the session.
    public enum TransferState {
        PROBING,                // Step 3 — probe in flight
        AWAITING_GATE,          // Step 4 — waiting for player decision (warning screen)
        AWAITING_PROFILE,       // Step 5 — profile selector open
        SENDING_DAT,            // Step 6 — sending profile dat to host
        AWAITING_HOST_PREP,     // Step 7 — waiting for host to build mirror portal etc.
        AWAITING_UUID_LIST,     // Step 8 — waiting for host UUID list
        DECONFLICTING,          // Step 9 — client running UUID deconfliction
        SENDING_UUID,           // Step 10 — sending agreed UUID to host
        AWAITING_READY_ECHO,    // Steps 11-12 — READY sent, waiting for echo
        COMPLETE,               // Step 13 — gate released, vanilla join running
        FAILED                  // Any timeout or error — session discarded
    }

    // -------------------------------------------------------
    // Session fields
    // -------------------------------------------------------

    // Unique key for this session — generated by the host during the probe
    public final String transferKey;

    // The address the player is connecting to (host:port)
    public final String targetAddress;

    // The address the player is coming from — used to link the mirror portal back
    // Only set on portal-path transfers; null on direct connect / server list
    public final String originAddress;

    // Whether this transfer came through a portal (true) or direct connect (false)
    public final boolean isPortalPath;

    // The UUID of the origin portal the player walked through
    // Only set when isPortalPath = true
    public final String originPortalUuid;

    // Whether Leap! Forward is present on this client
    public final boolean leapForwardPresent;

    // The current step this session is at
    public TransferState state;

    // Timestamp of when the current state was entered — used for timeout checking
    public long stateEnteredAt;

    // The UUID agreed upon after deconfliction — set during step 9/10
    public String agreedPortalUuid;

    // -------------------------------------------------------
    // Constructor
    // -------------------------------------------------------

    public TransferSession(String transferKey,
                           String targetAddress,
                           String originAddress,
                           boolean isPortalPath,
                           String originPortalUuid,
                           boolean leapForwardPresent) {
        this.transferKey = transferKey;
        this.targetAddress = targetAddress;
        this.originAddress = originAddress;
        this.isPortalPath = isPortalPath;
        this.originPortalUuid = originPortalUuid;
        this.leapForwardPresent = leapForwardPresent;
        this.state = TransferState.PROBING;
        this.stateEnteredAt = System.currentTimeMillis();
    }

    // Advances to the next state and resets the timeout clock
    public void advanceTo(TransferState newState) {
        this.state = newState;
        this.stateEnteredAt = System.currentTimeMillis();
    }

    // How many milliseconds this session has been in its current state
    public long millisInCurrentState() {
        return System.currentTimeMillis() - stateEnteredAt;
    }
}
